# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/System.xdc

# Block Designs: bd/System/System.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System || ORIG_REF_NAME==System}]

# IP: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}]

# IP: bd/System/ip/System_processing_system7_0_axi_periph_0/System_processing_system7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_processing_system7_0_axi_periph_0 || ORIG_REF_NAME==System_processing_system7_0_axi_periph_0}]

# IP: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}]

# IP: bd/System/ip/System_axi_fifo_mm_s_0_0/System_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==System_axi_fifo_mm_s_0_0}]

# IP: bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_0 || ORIG_REF_NAME==System_axi_gpio_0_0}]

# IP: bd/System/ip/System_xbar_0/System_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xbar_0 || ORIG_REF_NAME==System_xbar_0}]

# IP: bd/System/ip/System_axi_gpio_1_0/System_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_1_0 || ORIG_REF_NAME==System_axi_gpio_1_0}]

# IP: bd/System/ip/System_axi_gpio_3_0/System_axi_gpio_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_3_0 || ORIG_REF_NAME==System_axi_gpio_3_0}]

# IP: bd/System/ip/System_axi_gpio_2_0/System_axi_gpio_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_2_0 || ORIG_REF_NAME==System_axi_gpio_2_0}]

# IP: bd/System/ip/System_xlconstant_1_0/System_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconstant_1_0 || ORIG_REF_NAME==System_xlconstant_1_0}]

# IP: bd/System/ip/System_axi_gpio_4_0/System_axi_gpio_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_4_0 || ORIG_REF_NAME==System_axi_gpio_4_0}]

# IP: bd/System/ip/System_axi_gpio_5_0/System_axi_gpio_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_5_0 || ORIG_REF_NAME==System_axi_gpio_5_0}]

# IP: bd/System/ip/System_xadc_channel_14_0_0/System_xadc_channel_14_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xadc_channel_14_0_0 || ORIG_REF_NAME==System_xadc_channel_14_0_0}]

# IP: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_clk_wiz_0_0 || ORIG_REF_NAME==System_clk_wiz_0_0}]

# IP: bd/System/ip/System_ac_interface_0_0/System_ac_interface_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_ac_interface_0_0 || ORIG_REF_NAME==System_ac_interface_0_0}]

# IP: bd/System/ip/System_dds_compiler_1_0/System_dds_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_dds_compiler_1_0 || ORIG_REF_NAME==System_dds_compiler_1_0}]

# IP: bd/System/ip/System_xlslice_6_0/System_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_6_0 || ORIG_REF_NAME==System_xlslice_6_0}]

# IP: bd/System/ip/System_xlslice_7_0/System_xlslice_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_7_0 || ORIG_REF_NAME==System_xlslice_7_0}]

# IP: bd/System/ip/System_xlslice_3_0/System_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_3_0 || ORIG_REF_NAME==System_xlslice_3_0}]

# IP: bd/System/ip/System_cic_compiler_0_0/System_cic_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_cic_compiler_0_0 || ORIG_REF_NAME==System_cic_compiler_0_0}]

# IP: bd/System/ip/System_cordic_0_0/System_cordic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_cordic_0_0 || ORIG_REF_NAME==System_cordic_0_0}]

# IP: bd/System/ip/System_xlslice_5_0/System_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_5_0 || ORIG_REF_NAME==System_xlslice_5_0}]

# IP: bd/System/ip/System_cmpy_0_0/System_cmpy_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_cmpy_0_0 || ORIG_REF_NAME==System_cmpy_0_0}]

# IP: bd/System/ip/System_xlconcat_0_2/System_xlconcat_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconcat_0_2 || ORIG_REF_NAME==System_xlconcat_0_2}]

# IP: bd/System/ip/System_xlconcat_2_1/System_xlconcat_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconcat_2_1 || ORIG_REF_NAME==System_xlconcat_2_1}]

# IP: bd/System/ip/System_c_counter_binary_0_0/System_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_c_counter_binary_0_0 || ORIG_REF_NAME==System_c_counter_binary_0_0}]

# IP: bd/System/ip/System_mult_gen_0_1/System_mult_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_mult_gen_0_1 || ORIG_REF_NAME==System_mult_gen_0_1}]

# IP: bd/System/ip/System_xlslice_0_1/System_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_0_1 || ORIG_REF_NAME==System_xlslice_0_1}]

# IP: bd/System/ip/System_xlslice_1_1/System_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_1_1 || ORIG_REF_NAME==System_xlslice_1_1}]

# IP: bd/System/ip/System_switch_port_0_0/System_switch_port_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_switch_port_0_0 || ORIG_REF_NAME==System_switch_port_0_0}]

# IP: bd/System/ip/System_xlslice_2_0/System_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_2_0 || ORIG_REF_NAME==System_xlslice_2_0}]

# IP: bd/System/ip/System_delayz1z2_0_0/System_delayz1z2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_delayz1z2_0_0 || ORIG_REF_NAME==System_delayz1z2_0_0}]

# IP: bd/System/ip/System_c_addsub_0_0/System_c_addsub_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_c_addsub_0_0 || ORIG_REF_NAME==System_c_addsub_0_0}]

# IP: bd/System/ip/System_xlslice_4_0/System_xlslice_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_4_0 || ORIG_REF_NAME==System_xlslice_4_0}]

# IP: bd/System/ip/System_axi_gpio_6_0/System_axi_gpio_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_6_0 || ORIG_REF_NAME==System_axi_gpio_6_0}]

# IP: bd/System/ip/System_axi_gpio_7_0/System_axi_gpio_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_axi_gpio_7_0 || ORIG_REF_NAME==System_axi_gpio_7_0}]

# IP: bd/System/ip/System_switch_port_1_0/System_switch_port_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_switch_port_1_0 || ORIG_REF_NAME==System_switch_port_1_0}]

# IP: bd/System/ip/System_xlslice_8_0/System_xlslice_8_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_8_0 || ORIG_REF_NAME==System_xlslice_8_0}]

# IP: bd/System/ip/System_xlconcat_6_0/System_xlconcat_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconcat_6_0 || ORIG_REF_NAME==System_xlconcat_6_0}]

# IP: bd/System/ip/System_xlconstant_2_0/System_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconstant_2_0 || ORIG_REF_NAME==System_xlconstant_2_0}]

# IP: bd/System/ip/System_fir_compiler_1_0/System_fir_compiler_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_fir_compiler_1_0 || ORIG_REF_NAME==System_fir_compiler_1_0}]

# IP: bd/System/ip/System_switch_port_2_0/System_switch_port_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_switch_port_2_0 || ORIG_REF_NAME==System_switch_port_2_0}]

# IP: bd/System/ip/System_xlslice_12_0/System_xlslice_12_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_12_0 || ORIG_REF_NAME==System_xlslice_12_0}]

# IP: bd/System/ip/System_mult_gen_1_0/System_mult_gen_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_mult_gen_1_0 || ORIG_REF_NAME==System_mult_gen_1_0}]

# IP: bd/System/ip/System_dds_compiler_0_0/System_dds_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_dds_compiler_0_0 || ORIG_REF_NAME==System_dds_compiler_0_0}]

# IP: bd/System/ip/System_xlslice_14_0/System_xlslice_14_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_14_0 || ORIG_REF_NAME==System_xlslice_14_0}]

# IP: bd/System/ip/System_xlconcat_3_1/System_xlconcat_3_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconcat_3_1 || ORIG_REF_NAME==System_xlconcat_3_1}]

# IP: bd/System/ip/System_xlconstant_0_1/System_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconstant_0_1 || ORIG_REF_NAME==System_xlconstant_0_1}]

# IP: bd/System/ip/System_xlslice_16_0/System_xlslice_16_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_16_0 || ORIG_REF_NAME==System_xlslice_16_0}]

# IP: bd/System/ip/System_fir_compiler_0_0/System_fir_compiler_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_fir_compiler_0_0 || ORIG_REF_NAME==System_fir_compiler_0_0}]

# IP: bd/System/ip/System_mult_gen_2_0/System_mult_gen_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_mult_gen_2_0 || ORIG_REF_NAME==System_mult_gen_2_0}]

# IP: bd/System/ip/System_xlslice_9_0/System_xlslice_9_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_9_0 || ORIG_REF_NAME==System_xlslice_9_0}]

# IP: bd/System/ip/System_xlconcat_1_0/System_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconcat_1_0 || ORIG_REF_NAME==System_xlconcat_1_0}]

# IP: bd/System/ip/System_mult_gen_3_0/System_mult_gen_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_mult_gen_3_0 || ORIG_REF_NAME==System_mult_gen_3_0}]

# IP: bd/System/ip/System_mult_gen_4_0/System_mult_gen_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_mult_gen_4_0 || ORIG_REF_NAME==System_mult_gen_4_0}]

# IP: bd/System/ip/System_xlslice_10_0/System_xlslice_10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_10_0 || ORIG_REF_NAME==System_xlslice_10_0}]

# IP: bd/System/ip/System_xlslice_11_0/System_xlslice_11_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_11_0 || ORIG_REF_NAME==System_xlslice_11_0}]

# IP: bd/System/ip/System_xlslice_15_0/System_xlslice_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_15_0 || ORIG_REF_NAME==System_xlslice_15_0}]

# IP: bd/System/ip/System_xlslice_17_0/System_xlslice_17_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_17_0 || ORIG_REF_NAME==System_xlslice_17_0}]

# IP: bd/System/ip/System_xlslice_18_0/System_xlslice_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_18_0 || ORIG_REF_NAME==System_xlslice_18_0}]

# IP: bd/System/ip/System_xlconcat_4_0/System_xlconcat_4_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconcat_4_0 || ORIG_REF_NAME==System_xlconcat_4_0}]

# IP: bd/System/ip/System_switch_port_3_0/System_switch_port_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_switch_port_3_0 || ORIG_REF_NAME==System_switch_port_3_0}]

# IP: bd/System/ip/System_xlconcat_5_0/System_xlconcat_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconcat_5_0 || ORIG_REF_NAME==System_xlconcat_5_0}]

# IP: bd/System/ip/System_xlslice_21_0/System_xlslice_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_21_0 || ORIG_REF_NAME==System_xlslice_21_0}]

# IP: bd/System/ip/System_xlconstant_3_0/System_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconstant_3_0 || ORIG_REF_NAME==System_xlconstant_3_0}]

# IP: bd/System/ip/System_xlslice_13_0/System_xlslice_13_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlslice_13_0 || ORIG_REF_NAME==System_xlslice_13_0}]

# IP: bd/System/ip/System_xlconcat_7_0/System_xlconcat_7_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_xlconcat_7_0 || ORIG_REF_NAME==System_xlconcat_7_0}]

# IP: bd/System/ip/System_auto_pc_0/System_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_auto_pc_0 || ORIG_REF_NAME==System_auto_pc_0}]

# XDC: bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_processing_system7_0_0 || ORIG_REF_NAME==System_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==System_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==System_rst_processing_system7_0_100M_0}]

# XDC: bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/System/ip/System_axi_fifo_mm_s_0_0/System_axi_fifo_mm_s_0_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_0 || ORIG_REF_NAME==System_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_0_0 || ORIG_REF_NAME==System_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_xbar_0/System_xbar_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_1_0/System_axi_gpio_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_1_0 || ORIG_REF_NAME==System_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_1_0/System_axi_gpio_1_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_1_0/System_axi_gpio_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_1_0 || ORIG_REF_NAME==System_axi_gpio_1_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_3_0/System_axi_gpio_3_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_3_0 || ORIG_REF_NAME==System_axi_gpio_3_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_3_0/System_axi_gpio_3_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_3_0/System_axi_gpio_3_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_3_0 || ORIG_REF_NAME==System_axi_gpio_3_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_2_0/System_axi_gpio_2_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_2_0 || ORIG_REF_NAME==System_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_2_0/System_axi_gpio_2_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_2_0/System_axi_gpio_2_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_2_0 || ORIG_REF_NAME==System_axi_gpio_2_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_4_0/System_axi_gpio_4_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_4_0 || ORIG_REF_NAME==System_axi_gpio_4_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_4_0/System_axi_gpio_4_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_4_0/System_axi_gpio_4_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_4_0 || ORIG_REF_NAME==System_axi_gpio_4_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_5_0/System_axi_gpio_5_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_5_0 || ORIG_REF_NAME==System_axi_gpio_5_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_5_0/System_axi_gpio_5_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_5_0/System_axi_gpio_5_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_5_0 || ORIG_REF_NAME==System_axi_gpio_5_0}] {/U0 }]/U0 ]]

# XDC: ipshared/TD/xadc_ch14_bipol_v1_3/92a3b9cb/constrs_1/imports/Vivado/ZYBO_Master.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_xadc_channel_14_0_0 || ORIG_REF_NAME==System_xadc_channel_14_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_clk_wiz_0_0 || ORIG_REF_NAME==System_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_clk_wiz_0_0 || ORIG_REF_NAME==System_clk_wiz_0_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_ooc.xdc

# XDC: bd/System/ip/System_dds_compiler_1_0/System_dds_compiler_1_0_ooc.xdc

# XDC: bd/System/ip/System_cic_compiler_0_0/System_cic_compiler_0_0_ooc.xdc

# XDC: bd/System/ip/System_cordic_0_0/System_cordic_0_0_ooc.xdc

# XDC: bd/System/ip/System_cmpy_0_0/System_cmpy_0_0_ooc.xdc

# XDC: bd/System/ip/System_c_counter_binary_0_0/System_c_counter_binary_0_0_ooc.xdc

# XDC: bd/System/ip/System_mult_gen_0_1/System_mult_gen_0_1_ooc.xdc

# XDC: bd/System/ip/System_c_addsub_0_0/System_c_addsub_0_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_6_0/System_axi_gpio_6_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_6_0 || ORIG_REF_NAME==System_axi_gpio_6_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_6_0/System_axi_gpio_6_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_6_0/System_axi_gpio_6_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_6_0 || ORIG_REF_NAME==System_axi_gpio_6_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_7_0/System_axi_gpio_7_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_7_0 || ORIG_REF_NAME==System_axi_gpio_7_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_axi_gpio_7_0/System_axi_gpio_7_0_ooc.xdc

# XDC: bd/System/ip/System_axi_gpio_7_0/System_axi_gpio_7_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==System_axi_gpio_7_0 || ORIG_REF_NAME==System_axi_gpio_7_0}] {/U0 }]/U0 ]]

# XDC: bd/System/ip/System_fir_compiler_1_0/System_fir_compiler_1_0_ooc.xdc

# XDC: bd/System/ip/System_mult_gen_1_0/System_mult_gen_1_0_ooc.xdc

# XDC: bd/System/ip/System_dds_compiler_0_0/System_dds_compiler_0_0_ooc.xdc

# XDC: bd/System/ip/System_fir_compiler_0_0/System_fir_compiler_0_0_ooc.xdc

# XDC: bd/System/ip/System_mult_gen_2_0/System_mult_gen_2_0_ooc.xdc

# XDC: bd/System/ip/System_mult_gen_3_0/System_mult_gen_3_0_ooc.xdc

# XDC: bd/System/ip/System_mult_gen_4_0/System_mult_gen_4_0_ooc.xdc

# XDC: bd/System/ip/System_auto_pc_0/System_auto_pc_0_ooc.xdc

# XDC: bd/System/System_ooc.xdc
