# 
# Synthesis run script generated by Vivado
# 

set_param gui.test TreeTableDev
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000

create_project -in_memory -part xc7z010clg400-1
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/rd/vivado-outputs/XADC_3_DEM/XADC.cache/wt [current_project]
set_property parent.project_path /home/rd/vivado-outputs/XADC_3_DEM/XADC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths {
  /home/rd/zybo-audio/ac_interface
  /home/rd/vivado-outputs/ShiftSlice
  /home/rd/vivado-outputs/lcd16x2
  /home/rd/vivado-outputs/delayz1z2
  /home/rd/vivado-outputs/switch_out2n
  /home/rd/vivado-outputs/IP
  /home/rd/vivado-outputs/IP_VGA_VL
} [current_project]
add_files /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/System.bd
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_processing_system7_0_0/System_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_rst_processing_system7_0_100M_0/System_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_fifo_mm_s_0_0/System_axi_fifo_mm_s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_0_0/System_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_xbar_0/System_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_1_0/System_axi_gpio_1_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_1_0/System_axi_gpio_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_1_0/System_axi_gpio_1_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_3_0/System_axi_gpio_3_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_3_0/System_axi_gpio_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_3_0/System_axi_gpio_3_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_2_0/System_axi_gpio_2_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_2_0/System_axi_gpio_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_2_0/System_axi_gpio_2_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_4_0/System_axi_gpio_4_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_4_0/System_axi_gpio_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_4_0/System_axi_gpio_4_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_5_0/System_axi_gpio_5_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_5_0/System_axi_gpio_5_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_5_0/System_axi_gpio_5_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/ipshared/TD/xadc_ch14_bipol_v1_3/92a3b9cb/constrs_1/imports/Vivado/ZYBO_Master.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_clk_wiz_0_0/System_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_dds_compiler_1_0/System_dds_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_cic_compiler_0_0/System_cic_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_cordic_0_0/System_cordic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_cmpy_0_0/System_cmpy_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_c_counter_binary_0_0/System_c_counter_binary_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_mult_gen_0_1/System_mult_gen_0_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_c_addsub_0_0/System_c_addsub_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_6_0/System_axi_gpio_6_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_6_0/System_axi_gpio_6_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_6_0/System_axi_gpio_6_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_7_0/System_axi_gpio_7_0_board.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_7_0/System_axi_gpio_7_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_axi_gpio_7_0/System_axi_gpio_7_0.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_fir_compiler_1_0/System_fir_compiler_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_mult_gen_1_0/System_mult_gen_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_dds_compiler_0_0/System_dds_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_fir_compiler_0_0/System_fir_compiler_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_mult_gen_2_0/System_mult_gen_2_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_mult_gen_3_0/System_mult_gen_3_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_mult_gen_4_0/System_mult_gen_4_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/ip/System_auto_pc_0/System_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/System_ooc.xdc]
set_property is_locked true [get_files /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/bd/System/System.bd]

read_vhdl -library xil_defaultlib /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/sources_1/imports/hdl/System_wrapper.vhd
read_xdc /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/constrs_1/new/System.xdc
set_property used_in_implementation false [get_files /home/rd/vivado-outputs/XADC_3_DEM/XADC.srcs/constrs_1/new/System.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
catch { write_hwdef -file System_wrapper.hwdef }
synth_design -top System_wrapper -part xc7z010clg400-1
write_checkpoint -noxdef System_wrapper.dcp
catch { report_utilization -file System_wrapper_utilization_synth.rpt -pb System_wrapper_utilization_synth.pb }
